name: React Native
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository)
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 21.x
        uses: actions/setup-node@v2
        with:
          node-version: '21.x'
      - name: Install dependencies
        run: npm install && npm install --save-dev tailwindcss@3.3.2
      - name: Test
        run: npm test
